### ISSUE TITLE
Add Standard report layout

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh-documentation#1014]
#### Add the default standard layout for reports in jasper documentation
- see details here: https://github.com/metasfresh/me03/issues/12117#issuecomment-1149880160

**Comment by cristinamghita** [comment]
See here for an example of look and feel (Open Items report):
- https://github.com/metasfresh/me03/issues/12117#issuecomment-1149894446

**Comment by metas-Kay** [comment]
Documented here:
- [Standard Report Layout Definitions (Style Guide)](https://docs.metasfresh.org/jasper_reports_collection/EN/standard_report_layout_style_guide.html)
