### ISSUE TITLE
Create Translation section/page in Application Dictionary documentation

### ISSUE THREAD

**Issue by cristinastefan90** [metasfresh/metasfresh-documentation#1021]
New section called Translations needs to be added in here ⬇️ 
![image](https://user-images.githubusercontent.com/50820854/237037519-172ddc93-91c2-4501-b892-3e728c2252b0.png)

**Comment by cristinastefan90** [comment]
## 🔀 R&I to branch `master`

### PRs

- [ ] developer also looked over the PR
- https://github.com/metasfresh/metasfresh-documentation/pull/1025
  - review_URLs_here

<details>
<summary>TODOs for the reviewer</summary>

- [ ] make sure the target-system was set
- [ ] make sure the target-branch is consistent with the Hotfix-Y/N requirement
- [ ] make sure that setting the [`patch_mgmt`](https://github.com/metasfresh/me03/labels/patch_mgmt) label was considered and that the eventual decision makes sense
- [ ] make sure the expectable effort is within the `est:` and `bud:`
    - or if they aren't, make sure it was clarified with the issue-giver (->look for a comment it this issue)
- [ ] make sure the functional concept is consistent with the requirements
- [ ] make sure the technical concept is consistent with the requirements and functional concept
- [ ] understand the code changes if practical
    - https://github.com/metasfresh/me03/wiki/Code-review-guidelines
- [ ] understand the documented dev-tests and make sure they show that the problem is solved

</details>


### After integration

- [ ] set `branch:`-label in the PR and metasfresh-issue
  - [ ] reference the metasfresh-issue from the PR's description
- [ ] set `branch:`-label in customer-issue
- [ ] set customer milestone (either hotfix milestone or "normal" UAT milestone)
- [ ] if needed, set `rm:manual_rollout`-label in customer-issue
- if PR is done in public metasfresh-metasfresh repository
  - [ ] set `added2mf/mf`-label in me03-issue 
  - [ ] integrate (merge) your customer-branch => `master` (don't squash multiple issues!), set the `branch:master label` and add the link to the top of https://github.com/metasfresh/metasfresh/blob/master/ReleaseNotes.md
    - ❗ Make sure it works before pushing to master ❗ 
      This can be done by pushing an integration-branch that contains master and your customer-branch

**Comment by metas-Kay** [comment]
### Documented in Application Dictionary Docs

- [Add customer-specific translations to system element (AD_Element_Trl)](https://docs.metasfresh.org/appdictionary_collection/EN/AD_Element_Trl_customization.html)
