### ISSUE TITLE
new swagger link 

### ISSUE THREAD

**Issue by andreasokn** [metasfresh/metasfresh-documentation#1022]
Please change documentation https://docs.metasfresh.org/installation_collection/EN/How_do_I_browse_the_REST_API_using_Swagger.html and use this swagger link https://github.com/metasfresh/bc107/issues/550#issuecomment-1541573769

**Comment by MHNV** [comment]
PR:
- https://github.com/metasfresh/metasfresh-documentation/pull/1023

**Comment by andreasokn** [comment]
# Customer closed
https://github.com/metasfresh/bc107/issues/550#issuecomment-1541626298

**Comment by metas-Kay** [comment]
# Please note
This change/update also affects other docs:
- https://docs.metasfresh.org/rest_api_collection/DE/Allgemeine_Infos_REST_API.html
- https://docs.metasfresh.org/rest_api_collection/EN/General_info_REST_API.html
- https://docs.metasfresh.org/installation_collection/DE/REST_API_durchsuchen_mittels_Swagger.html
- https://docs.metasfresh.org/installation_collection/EN/How_do_I_browse_the_REST_API_using_Swagger.html
- https://docs.metasfresh.org/installation_collection/DE/Entwickleransicht_mittels_Swagger_aktivieren.html
- https://docs.metasfresh.org/installation_collection/EN/How_do_I_enable_developer_view_using_Swagger.html

## Questions for clarification
As a result of this update, this URL:
- `http://<yourserver:port>/swagger-ui.html#!/debug-rest-controller/setShowColumnNamesForCaptionUsingPUT`
in this doc, for example:
- https://docs.metasfresh.org/installation_collection/DE/Entwickleransicht_mittels_Swagger_aktivieren.html

has to be:
- `https://<yourserver:port>/app/swagger-ui/index.html#/debug-rest-controller/setShowColumnNamesForCaptionUsingPUT`

correct❓

:question: What about the `!` after the `html#`? The `#` seems to be important:
- `https://<yourserver:port>/app/swagger-ui/index.html#/app-server-migration-script-rest-controller` => OK
- `https://<yourserver:port>/app/swagger-ui/index.html/app-server-migration-script-rest-controller` => Whitelabel Error Page

:question: Thus, can the `!` be omitted or is it necessary specifically for the `debug-rest-controller`?

:question: And is the `index.html` strictly necessary or can it be omitted?
Both versions work:
- `https://<yourserver:port>/app/swagger-ui/`
- `https://<yourserver:port>/app/swagger-ui/index.html`

And if I open an API endpoint, just a `#/` is added:
- `https://<yourserver:port>/app/swagger-ui/#/app-server-migration-script-rest-controller`
- `https://<yourserver:port>/app/swagger-ui/index.html#/app-server-migration-script-rest-controller`

**Comment by MHNV** [comment]
@metas-Kay 
> has to be:
> - https://<yourserver:port>/app/swagger-ui/index.html#/debug-rest-controller/setShowColumnNamesForCaptionUsingPUT

🅰️: yes thats how it should look like

> ❓ What about the ! after the html#? The # seems to be important:

🅰️: Afaik the `#` is only important when you want to zoom to a section like `/app-server-migration-script-rest-controller` it always adds the `#` infront of the section. So if you only want to go to the swagger-ui you only need the `/app/swagger-ui/index.html` to get there. 

> ❓ Thus, can the ! be omitted or is it necessary specifically for the debug-rest-controller?

🅰️: I remember that the swagger-UI used to use`!`, but I saw that its not used anymore after the swagger-ui changes.

> ❓ And is the `index.html` strictly necessary or can it be omitted?

🅰️:  Afaik it can be omitted on some customer site, but  on some other it doens't work. I think we could add a section to show the full link with `index.html`. Since for me the `index.html` shows me that im on swagger-ui and Im on the `index.html` page of the swagger-ui.

**Comment by metas-Kay** [comment]
# Updated docs

## English Versions
- https://docs.metasfresh.org/rest_api_collection/EN/General_info_REST_API.html
- https://docs.metasfresh.org/rest_api_collection/EN/How_do_I_browse_the_REST_API_using_Swagger.html
    >**Note:** Moved from [installation collection](https://docs.metasfresh.org/pages/installation/index_en) due to its relatedness to the REST API topic.
- https://docs.metasfresh.org/rest_api_collection/EN/set_user_session_language_via_swagger.html
- https://docs.metasfresh.org/rest_api_collection/EN/enable_developer_view_via_Swagger.html
    >**Note:** Moved from [installation collection](https://docs.metasfresh.org/pages/installation/index_en) due to its relatedness to the REST API topic
- https://docs.metasfresh.org/installation_collection/EN/How_do_I_enable_developer_view_using_Swagger.html
    >**Note:** Kept as a reference doc linking to the [actual guide in the REST API collection](https://docs.metasfresh.org/rest_api_collection/EN/enable_developer_view_via_Swagger.html).
- https://docs.metasfresh.org/support_collection/en/change_language_metasfresh_user.html

## German Versions
- https://docs.metasfresh.org/rest_api_collection/DE/Allgemeine_Infos_REST_API.html
- https://docs.metasfresh.org/rest_api_collection/DE/REST_API_durchsuchen_mittels_Swagger.html
    >**Note:** Moved from [installation collection](https://docs.metasfresh.org/pages/installation/index_de) due to its relatedness to the REST API topic.
- https://docs.metasfresh.org/rest_api_collection/DE/Sprache_Benutzersitzung_via_Swagger_einstellen.html
- https://docs.metasfresh.org/rest_api_collection/DE/Entwickleransicht_via_Swagger_aktivieren.html
    >**Note:** Moved from [installation collection](https://docs.metasfresh.org/pages/installation/index_de) due to its relatedness to the REST API topic
- https://docs.metasfresh.org/installation_collection/DE/Entwickleransicht_mittels_Swagger_aktivieren.html
    >**Note:** Kept as a reference doc linking to the [actual guide in the REST API collection](https://docs.metasfresh.org/rest_api_collection/DE/Entwickleransicht_via_Swagger_aktivieren.html).
