### ISSUE TITLE
Create documentation for new cloning feature

### ISSUE THREAD

**Issue by cristinastefan90** [metasfresh/metasfresh-documentation#1043]
We have a new way of cloning the records and their respective entries in the subtabs.

I would like to have this documentation: https://github.com/metasfresh/me03/issues/15739#issuecomment-1592495203

Published here: https://docs.metasfresh.org/pages/appdictionary/index_en.html

**Comment by metas-Kay** [comment]
The new doc can be found here:
- https://docs.metasfresh.org/appdictionary_collection/EN/configurable_cloning_feature

<kbd><img src="https://github.com/metasfresh/metasfresh-documentation/assets/29163573/8903ce13-244b-4f4e-80f5-8ce09c5f7f40"></kbd>
