### ISSUE TITLE
Add documentation about excel template reports with jxls

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-documentation#1044]
Please, put the content of this message in a documentation file : https://github.com/metasfresh/me03/issues/16163#issuecomment-1695841844

Target audience for the documentation: metasfresh devs

**Comment by metas-Kay** [comment]
Added new section "Excel Report Templates (Jxls)" to **Application Dictionary Guide**.
- [How to add columns to an Excel template](https://docs.metasfresh.org/appdictionary_collection/EN/excel_report_templates_add_columns.html)
- [How to protect and unprotect Excel sheets with a password](https://docs.metasfresh.org/appdictionary_collection/EN/excel_report_protect_unprotect_sheet.html)
- [How to make a cell read-only in an Excel sheet (lock cell)](https://docs.metasfresh.org/appdictionary_collection/EN/excel_report_lock_cell_read-only.html)
- [How to hide entire columns in an Excel sheet](https://docs.metasfresh.org/appdictionary_collection/EN/excel_report_hide_columns.html)

<kbd><img src="https://github.com/metasfresh/metasfresh-documentation/assets/29163573/d656e03c-56eb-4c47-98f4-bbd780cc6e5d"></kbd>
