### ISSUE TITLE
Partner related products

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#151]

**Comment by metasnw** [comment]
@metas-Kay as products can have partner specific name AND number I ask myself it was better to name the manual "How do I manage partner-related products" (without "name")
WDYT?

**Comment by metas-Kay** [comment]
@metasnw Yes you are right. How about we call the manual "How do I manage partner-related products" and replace "prouct name" by "product information" in the documentation in order to refer to both, name and number?

**Comment by metasnw** [comment]
@metas-Kay 
I am fine with the name change.
> replace "prouct name" by "product information"
I think I would rather be precise on this and list product name and number explicitly

**Comment by metas-Kay** [comment]
@metasnw Good point! On it.
