### ISSUE TITLE
Update documentation on keyboard shortcuts for WebUI

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-documentation#234]
Pls update the documentation on keyboard shortcuts for WebUI according to the latest changes

**Comment by metas-Kay** [comment]
I have checked all shortcuts and have found that the documentation is up to date.
Please comment the out-of-date shortcuts in case I have missed sth.

The following shortcuts do not work yet:
- FIRST_PAGE: "Home" (Pagination context)
- OPEN_ADVANCED_EDIT: `${mod}+E` (Document context, no selection)

(ref: https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/src/shortcuts/keymap.js)
