### ISSUE TITLE
Document how to define prices in EN+DE

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-documentation#236]
Describe:
- Price system
- Price lists
- Price list versions
- Price

**Comment by metas-dh** [comment]
* Link to "Ordne die Preise einem Partner zu." on page http://docs.metasfresh.org/webui_collection/DE/Preis_anlegen: 404 Error (working fine in EN version)
* add a price: also possible in window Product, first tab: @metasnw do we want to include this in the documentation as well?

**Comment by metasnw** [comment]
@metas-dh good idea.
@metas-Kay can you add it please?

**Comment by metas-Kay** [comment]
@metasnw & @metas-dh :

Instructions for "add price" in product window already exists. Please see:
http://docs.metasfresh.org/webui_collection/DE/ProduktPreis.html
http://docs.metasfresh.org/webui_collection/EN/ProductPrice.html

---

Will fix link in DE
