### ISSUE TITLE
add documentation how to assign price system to partner group

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#241]
extend 
http://docs.metasfresh.org/webui_collection/EN/Assign_prices_to_partner.html

## how to

1. click on the partner group field of a partner using http://docs.metasfresh.org/webui_collection/EN/Jumpto.html
![image](https://user-images.githubusercontent.com/16079655/34868616-a91ee34e-f784-11e7-850f-a6c8d2667093.png)

2. in the window partner group fill out the field price system

**Comment by metas-Kay** [comment]
"In order to obtain a sales price list you have to check the box Sales Price List in the corresponding price list entry. [...]"
- Add comment with link to *ref Add_price-list* in brackets: (Step 8 of "How do I add a price list") for clearer comprehension in EN+DE
