### ISSUE TITLE
Update docu on Group Discounts

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-documentation#274]
The action for group discounts has a different name, plus there are 2 different actions now for the 1st group discount and the successive discount. 
Pls update http://docs.metasfresh.org/webui_collection/EN/Order_line_group_discount.html &
http://docs.metasfresh.org/webui_collection/DE/Auftragszeilengruppenrabatt.html
 accordingly.

**Comment by metas-Kay** [comment]
Also add description on how to create a price list scheme and subsequent to this update refs *copy_prices_from_price-list-version* & *price_list_scheme_rules*.

**Comment by metas-Kay** [comment]
Add note on "Valid from date" in ref automatic_discount_scheme:
 >**Note:** If this date lies in the *past* the discount scheme is effective *immediately*. If it lies in the *future* the scheme will only apply *from that date*.

**Comment by metas-Kay** [comment]
Also add documentation on "Automatic group creation in sales order lines" (https://github.com/metasfresh/metasfresh-webui-api/issues/853) in EN+DE
