### ISSUE TITLE
Marketing&Cleverreach: Setup Cleverreach interface

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#309]

**Comment by metas-Kay** [comment]
- https://github.com/metasfresh/metasfresh/issues/4030 (windows for MKTG and CR)
- https://github.com/metasfresh/metasfresh/issues/4031 (Add Users to Newsletter MKTG campaign)
- https://github.com/metasfresh/metasfresh/issues/4015 (CR interface)

**Comment by metas-Kay** [comment]
- [ ] Update docs on how to set up a marketing platform using CleverReach, i.e. add steps describing how to open the record tab "CleverReach" and add the user details
 EN: https://docs.metasfresh.org/webui_collection/EN/Create_MKTG_platform.html
 DE: https://docs.metasfresh.org/webui_collection/DE/MKTG-Plattform_erstellen.html
