### ISSUE TITLE
Add Partner group to documentation price list versus price system

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#443]

**Comment by metas-Kay** [comment]
- also update http://docs.metasfresh.org/webui_collection/DE/Zuweisung_Preise_Partner as follows:

### Assign Price List to Partner Group

1. Open the entry of an existing business partner or add a new one.
1. ...

=> Don't start with BP entry, start with BP group directly, maybe add alternative via BP entry (jump to via field)
==> perhaps even create separate doc for BP group (easy to overlook in current version, bc it comes after the first example. Usually an example is the last part of doc)
