### ISSUE TITLE
Describe how to apply database changes during update using docker

### ISSUE THREAD

**Issue by daveyx** [metasfresh/metasfresh-documentation#55]
During update metasfresh docker installation, the migration scripts must be applied to the existing database. Improve documentation in
[How_do_I_update_metasfresh_using_Docker](https://github.com/metasfresh/metasfresh-documentation/blob/master/_installation_collection/EN/How_do_I_update_metasfresh_using_Docker.md)
and
[Wie_aktualisiere_ich_metasfresh_mittels_Docker](https://github.com/metasfresh/metasfresh-documentation/blob/master/_installation_collection/DE/Wie_aktualisiere_ich_metasfresh_mittels_Docker.md)

I found information about that:
[serverupdate](http://metasfresh.com/dokumentation/serverupdate/)
[sql_remote.sh](https://github.com/metasfresh/metasfresh/blob/master/de.metas.scripts.rollout/src/main/bash/sql_remote.sh)
[RolloutMigrate.java](https://github.com/metasfresh/metasfresh/blob/master/de.metas.migration/de.metas.migration.cli/src/main/java/de/metas/migration/cli/RolloutMigrate.java)

Is it enough just to login to metasfreshdocker_app_1 and run
./opt/metasfresh/dist/install/sql_remote.sh ?

**Comment by daveyx** [comment]
i just updated my docker and i see that the scripts are applied automatically by metasfresh backend. 

no nothing to do in addition except running container metasfreshdocker_app_1
right?

**Comment by metas-jb** [comment]
Correct.

Every time the container `app` is started `sql_remote.sh` is executed to update the database found in the container `db`.

So if you pull/create a new version of `app` including fixes and migration scripts, you just need to remove the build-container for app (`docker-compose rm`) and rebuild it with the corresponding image-name for the new image in `./app/Dockerfile`.

On the next start of the new containers the `app` container will execute `sql_remote.sh` and will update your database.

**Comment by daveyx** [comment]
thx @metas-jb for clarification, closed
