### ISSUE TITLE
add recommendation for visualize docker containers

### ISSUE THREAD

**Issue by daveyx** [metasfresh/metasfresh-documentation#60]
add recommendation for visualize docker containers in
[How_do_I_setup_the_metasfresh_stack_using_Docker](https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_installation_collection/EN/How_do_I_setup_metasfresh_docker_with_ssl.md)
[Wie_installiere_ich_den_metasfresh_Stack_mit_Docker](https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_installation_collection/DE/Wie_installiere_ich_den_metasfresh_Stack_mit_Docker.md)

**Comment by metas-ts** [comment]
Btw, at @daveyx  you also know about tools that support docker-compose?

**Comment by daveyx** [comment]
Hi @metas-ts, unfortunately not
