### ISSUE TITLE
Record permission feature

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-documentation#733]
https://github.com/metasfresh/metasfresh/issues/5970

BPartner window / actions menu:
![image](https://user-images.githubusercontent.com/29163573/72443763-1affd600-37af-11ea-979a-e1b2f8cae592.png)

**Comment by teosarca** [comment]
@metas-Kay  isn't this already done long time ago?

**Comment by metas-Kay** [comment]
@teosarca Feature is now documented, please see below:

- EN: [How to grant and revoke data access to users](https://docs.metasfresh.org/webui_collection/EN/Manage_user_permission.html)
- DE: [Nutzern Datenzugriff gewähren/entziehen](https://docs.metasfresh.org/webui_collection/DE/Zugriffsberechtigung_Nutzer_verwalten.html)
