### ISSUE TITLE
links in dev-docs are broken (error 404)

### ISSUE THREAD

**Issue by eckad158** [metasfresh/metasfresh-documentation#786]
Hi !
It seems as if all links in the dev documents are broken (error 404).
-> https://docs.metasfresh.org/pages/developers/index_en

You can still access the package descriptions from the docs but the links in the documents are now dead. I think this is related to the source code refacoring which happened a few days ago.

The documents contain links to the source code files which were now moved in the main repository.

**Comment by metas-Kay** [comment]
Checked all links. All appear to be working. No problems detected. => Closing.
