### ISSUE TITLE
Compare manuals DE <-> EN

### ISSUE THREAD

**Issue by Bartmann77** [metasfresh/metasfresh-documentation#82]
http://docs.metasfresh.org/pages/webui/index_de
http://docs.metasfresh.org/pages/webui/index_en

list of missing documents in EN

**Comment by metasnw** [comment]
@Bartmann77 assigning the issue to Kay to move on

**Comment by metas-Kay** [comment]
- Updating/adding references for eventual language links
- checking grammar and spelling, missing icons etc.
- translating missing documents

**Comment by metasnw** [comment]
all files now have a reference both in DE and EN
