### ISSUE TITLE
Adjust "How to switch interface language" DE&EN

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-documentation#84]
Adjust description "how to switch interface language" in the user manual by changing info to the new feature (rabbit symbol).
New gif needed.

**Comment by metasnw** [comment]
done
http://docs.metasfresh.org/webui_collection/EN/SwitchLanguage.html
http://docs.metasfresh.org/webui_collection/DE/SwitchLanguage.html
