### ISSUE TITLE
How to setup Atom for contributing docs - Enable GitHub Style

### ISSUE THREAD

**Issue by pauljakobseidenstuecker** [metasfresh/metasfresh-documentation#933]
In the setup guide for Atom there are some small mistakes:

- Enable Github Style
  - Step 2 & 3: change "install packages and themes" to "Installed Packages"
    (package `autocomplete-paths`  is already installed)

- Small:
  - Atom writes "install" with a capital letter.
  - "Github" is spelled "GitHub".

**Comment by metas-Kay** [comment]
@pauljakobseidenstuecker 
Thanks Pijay. Your commit has been merged.

General note for future reference: When referencing a doc, please also [add a link to it](https://docs.metasfresh.org/contributors_guide_collection/EN/how_to_setup_atom_for_contributing_docs.html) for quick(er) access in your comment.

https://docs.metasfresh.org/contributors_guide_collection/EN/how_to_setup_atom_for_contributing_docs.html
