### ISSUE TITLE
Translate Docker Installation to en_US

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#95]
http://docs.metasfresh.org/installation_collection/DE/Wie_installiere_ich_den_metasfresh_Stack_mit_Docker.html
was recently updated. changes need to be translated to:
http://docs.metasfresh.org/installation_collection/EN/How_do_I_setup_the_metasfresh_stack_using_Docker.html

**Comment by Bartmann77** [comment]
Done. Changed some minor formatting problems in german version as well.
